var covers = [
  './assets/captain-romance.jpg',
  './assets/bluebrocade.jpg',
  './assets/cherry.jpg',
  './assets/dance.jpg',
  './assets/hot-rod-hot-bod.jpg',
  './assets/embrace.png',
  './assets/fire.png',
  './assets/frock.png',
  './assets/romance-on-a-bench.jpg',
  './assets/glorious.jpg',
  './assets/golden.jpg',
  './assets/black-pink.jpg',
  './assets/price-of-royalty.jpg',
  './assets/masquerade.jpg',
  './assets/where-love-is-legal.jpg',
  './assets/moonlitmeadow.jpg',
  './assets/office.png',
  './assets/picnic.jpg',
  './assets/pirate.jpg',
  './assets/orange.jpg',
  './assets/prairie.jpg',
  './assets/hoodie-passion.jpg',
  './assets/regency.jpg',
  './assets/ribbons.jpg',
  './assets/roses.jpg',
  './assets/forest-love.jpg',
  './assets/ruffles.jpg',
  './assets/desert-hope.jpg',
  './assets/shine.png',
  './assets/smolder.png',
  './assets/transylvania-romance.jpg',
  './assets/snow.jpg',
  './assets/sparkles.jpg',
  './assets/stripes.png',
  './assets/wildwest.jpg',
  './assets/windswept.jpg',
  './assets/cuffed-affair.jpg',
];

var titles = [
  "Passionate Moonlight",
  "Musty in the Morning",
  "Eye of the Potato",
  "Roses and Flame",
  "Prairie Impropriety",
  "Stealthy Stranger",
  "Cuffed Affair",
  "Dirty Little Proposal",
  "Harvest of Heartache",
  "Stolen Innocence",
  "Silk and Stalking...",
  "Palpitations of Desire",
  "Romantic Imposters",
  "Steal the Heart",
  "The Price of Royalty",
  "Secrets and Silk",
  "Dreams of Fire",
  "Hard Harvest",
  "Peasants of the Forest",
  "Loving Thy Enemy",
  "Passion's Embrace",
  "Harbinger by Moonlight",
  "Burning Rouge Red",
  "Brown Chicken, Brown Cow",
  "Balcony Pleasures",
  "Seductive Cornfields",
  "Moonlit Mysteries",
  "Crimson Roses",
  "Destiny's Fires",
  "Proposals and Passion",
  "Silk Wedding",
  "Pirate's Booty",
  "Masked Seduction",
  "Crimson Masquerade",
  "Stole His Rubies",
  "Lurking Eyes",
  "Sapphires Seduction",
  "Opals for Love",
  "Crumbs of a Lover",
];

var descriptors = [
  "passion",
  "covfefe",
  "glory",
  "romance",
  "peanuts",
  "peasants",
  "woe",
  "picnics",
  "sorrow",
  "panic",
  "sweat",
  "patriarchy",
  "pain",
  "ardor",
  "fiddlesticks",
  "devotion",
  "genetically-modified seed",
  "potatoes",
  "weevils",
  "excitement",
  "rat-infestations",
  "fervor",
  "rage",
  "spirit",
  "disparity",
  "zeal",
  "ecstasy",
  "ire",
  "fire",
  "storms",
  "poppycock",
  "tempests",
  "feast",
  "rapture",
  "Scabies",
  "jealousy",
  "exhilaration",
  "bliss",
  "Hot Pockets",
  "filth",
  "barrel bottoms",
  "enchantment",
  "paradise",
  "calamity",
  "disaster",
  "heartache",
  "misfortune",
  "agony",
  "rigamarole",
  "curses",
  "Cholera",
  "blessings",
  "melancholy",
  "famine",
  "bankruptcy",
];
