var covers = [
  './assets/captain-romance.jpg',
  // './assets/bluebrocade.jpg',
  './assets/dance.jpg',
  './assets/hot-rod-hot-bod.jpg',
  './assets/embrace.png',
  './assets/fire.png',
  './assets/frock.png',
  './assets/romance-on-a-bench.jpg',
  './assets/glorious.jpg',
  './assets/golden.jpg',
  // './assets/maskedmeeting.jpg',
  './assets/price-of-royalty.jpg',
  './assets/masquerade.jpg',
  './assets/where-love-is-legal.jpg',
  './assets/moonlitmeadow.jpg',
  './assets/office.png',
  './assets/picnic.jpg',
  './assets/pirate.jpg',
  './assets/orange.jpg',
  // './assets/prairie.jpg',
  // './assets/redrenaissance.jpg',
  './assets/regency.jpg',
  './assets/ribbons.jpg',
  './assets/roses.jpg',
  './assets/forest-love.jpg',
  './assets/ruffles.jpg',
  // './assets/scroll.jpg',
  './assets/shine.png',
  './assets/smolder.png',
  './assets/transylvania-romance.jpg',
  './assets/snow.jpg',
  './assets/sparkles.jpg',
  './assets/stripes.png',
  './assets/wildwest.jpg',
  './assets/windswept.jpg',
  './assets/cuffed-affair.jpg'
];

var titles = [
  "Passionate Moonlight",
  "Love's Misery",
  "Eye of the Potato",
  "Roses and Flame",
  "Cuffed Affair",
  "Dirty Little Proposal",
  "Harvest of Heartache",
  "Innocent Roses",
  "Silk and Sense",
  "Hearts Aflame",
  "Fiery Passion",
  "Stolen Hearts",
  "The Price of Royalty",
  "Secrets and Silk",
  "Dreams of Fire",
  "Hard Harvest",
  "Peasants of the Forest",
  "Lovers and Enemies",
  "Passion's Embrace",
  "Harbinger by Moonlight",
  "Rouge Red",
  "Seductive Cornfields",
  "Moonlit Mysteries",
  "Crimson Roses",
  "Destiny's Fires",
  "Proposals and Passion",
  "Silk Wedding",
  "Pirate's Booty",
  "Masked Seduction",
  "Crimson Masquerade",
  "Stolen Rubies",
  "Emerald Eyes",
  "Sapphire Skies",
  "Opal Passions",
  "Crumbs of a Lover",
];

var descriptors = [
  "passion",
  "covfefe",
  "glory",
  "romance",
  "peasants",
  "woe",
  "picnics",
  "sorrow",
  "patriarchy",
  "pain",
  "ardor",
  "fiddlesticks",
  "devotion",
  "genetically-modified seed",
  "potatoes",
  "weevils",
  "excitement",
  "fervor",
  "rage",
  "spirit",
  "desparity",
  "zeal",
  "rat-infestations",
  "ecstasy",
  "fire",
  "storms",
  "poppycock",
  "tempests",
  "feast",
  "rapture",
  "ire",
  "Scabies",
  "jealousy",
  "exhilaration",
  "bliss",
  "Hot Pockets",
  "filth",
  "enchantment",
  "paradise",
  "calamity",
  "disaster",
  "heartache",
  "misfortune",
  "agony",
  "rigamarole",
  "curses",
  "Cholera",
  "blessings",
  "melancholy",
  "famine",
  "bankruptcy",
];
